import * as fs from 'fs';
import * as path from 'path';
import { DayZServerConfig } from '../config/schema';

export class ServerConfigGenerator {
  private config: DayZServerConfig;

  constructor(config: DayZServerConfig) {
    this.config = config;
  }

  /**
   * Generate serverDZ.cfg content
   */
  generateServerConfig(): string {
    const server = this.config.server;
    const modConfigs = this.config.modConfigs;

    let config = `// DayZ Server Configuration
// Generated by dayz-manager

hostname = "${server.name}";
`;

    if (server.password) {
      config += `password = "${server.password}";\n`;
    }

    config += `passwordAdmin = "${server.adminPassword}";
maxPlayers = ${server.maxPlayers};

verifySignatures = ${server.verifySignatures};
forceSameBuild = 0;

disableVoN = 0;
vonCodecQuality = 20;

disable3rdPerson = ${server.disableThirdPerson ? 1 : 0};
disableCrosshair = ${server.disableCrosshair ? 1 : 0};

serverTime = "SystemTime";
serverTimeAcceleration = ${server.timeAcceleration ?? 1};
serverNightTimeAcceleration = ${server.nightTimeAcceleration ?? 1};
serverTimePersistent = ${server.persistent ? 1 : 0};

guaranteedUpdates = 1;

loginQueueConcurrentPlayers = 5;
loginQueueMaxPlayers = 500;

instanceId = 1;
storeHouseStateDisabled = false;

respawnTime = 5;

motd[] = {${this.formatMotd(server.motd)}};
motdInterval = 200;

enableDebugMonitor = 0;

// Steam query port (required for server browser visibility)
steamQueryPort = ${server.steamQueryPort};

// Mission selection
class Missions
{
    class DayZ
    {
        template = "${server.mission}";
    };
};

// BattlEye
BattlEye = ${server.battleEye ? 1 : 0};
`;

    // Add VPP Admin Tools specific config
    if (modConfigs?.vppAdminTools?.disablePassword) {
      config += `
// VPP Admin Tools - Disable password requirement
vppDisablePassword = 1;
`;
    }

    return config;
  }

  /**
   * Generate the startup script
   */
  generateStartupScript(): string {
    const server = this.config.server;
    const clientMods = this.config.mods.map(m => m.name);
    const serverMods = this.config.mods.filter(m => m.serverSide).map(m => m.name);

    let modParam = '';
    if (clientMods.length > 0) {
      modParam = `"-mod=${clientMods.join(';')}"`;
    }

    let serverModParam = '';
    if (serverMods.length > 0) {
      serverModParam = `"-serverMod=${serverMods.join(';')}"`;
    }

    return `#!/bin/bash
# DayZ Server Startup Script
# Generated by dayz-manager

SERVER_DIR="${this.config.paths.serverInstall}"
PROFILES_DIR="${this.config.paths.profiles}"

cd "$SERVER_DIR"

./DayZServer \\
    -config=serverDZ.cfg \\
    -port=${server.port} \\
    -profiles="$PROFILES_DIR" \\
    ${modParam} \\
    ${serverModParam} \\
    -BEpath=battleye \\
    -dologs \\
    -adminlog \\
    -netlog \\
    -freezecheck
`;
  }

  /**
   * Write all server configuration files
   */
  writeConfigs(): void {
    const serverPath = this.config.paths.serverInstall;
    const profilesPath = this.config.paths.profiles;

    // Ensure directories exist
    fs.mkdirSync(serverPath, { recursive: true });
    fs.mkdirSync(profilesPath, { recursive: true });

    // Write serverDZ.cfg
    const serverConfigPath = path.join(serverPath, 'serverDZ.cfg');
    fs.writeFileSync(serverConfigPath, this.generateServerConfig());
    console.log(`📝 Written: ${serverConfigPath}`);

    // Write startup script
    const startupScriptPath = path.join(serverPath, 'start-server.sh');
    fs.writeFileSync(startupScriptPath, this.generateStartupScript());
    fs.chmodSync(startupScriptPath, '755');
    console.log(`📝 Written: ${startupScriptPath}`);
  }

  private formatMotd(motd?: string[]): string {
    if (!motd || motd.length === 0) {
      return '"Welcome to the server!"';
    }
    return motd.map(line => `"${line}"`).join(', ');
  }
}

